
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Build started 08-04-2023 12:23:22.
      Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.06
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Build started 08-04-2023 12:23:23.
      Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.71
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-bb1nvu"
      binary: "C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-bb1nvu"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-bb1nvu
        
        Run Build Command(s):D:/vs/1/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_97843.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Build started 08-04-2023 12:23:24.
        Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-bb1nvu\\cmTC_97843.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_97843.dir\\Debug\\".
          Creating directory "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-bb1nvu\\Debug\\".
          Creating directory "cmTC_97843.dir\\Debug\\cmTC_97843.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_97843.dir\\Debug\\cmTC_97843.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_97843.dir\\Debug\\\\" /Fd"cmTC_97843.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31933 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_97843.dir\\Debug\\\\" /Fd"cmTC_97843.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-bb1nvu\\Debug\\cmTC_97843.exe" /INCREMENTAL /ILK:"cmTC_97843.dir\\Debug\\cmTC_97843.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-bb1nvu/Debug/cmTC_97843.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-bb1nvu/Debug/cmTC_97843.lib" /MACHINE:X64  /machine:x64 cmTC_97843.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_97843.vcxproj -> C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-bb1nvu\\Debug\\cmTC_97843.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_97843.dir\\Debug\\cmTC_97843.tlog\\unsuccessfulbuild".
          Touching "cmTC_97843.dir\\Debug\\cmTC_97843.tlog\\cmTC_97843.lastbuildstate".
        Done Building Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-bb1nvu\\cmTC_97843.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.73
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-58k6i7"
      binary: "C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-58k6i7"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-58k6i7
        
        Run Build Command(s):D:/vs/1/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_54ccf.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Build started 08-04-2023 12:23:25.
        Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-58k6i7\\cmTC_54ccf.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_54ccf.dir\\Debug\\".
          Creating directory "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-58k6i7\\Debug\\".
          Creating directory "cmTC_54ccf.dir\\Debug\\cmTC_54ccf.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_54ccf.dir\\Debug\\cmTC_54ccf.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_54ccf.dir\\Debug\\\\" /Fd"cmTC_54ccf.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31933 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_54ccf.dir\\Debug\\\\" /Fd"cmTC_54ccf.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\vs\\1\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-58k6i7\\Debug\\cmTC_54ccf.exe" /INCREMENTAL /ILK:"cmTC_54ccf.dir\\Debug\\cmTC_54ccf.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-58k6i7/Debug/cmTC_54ccf.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/vigop/OneDrive/backup 1/coding/Shadow Tech Software 2/visual studio 2019/Time Tinkerers/Time Tinkerers/CMakeFiles/CMakeScratch/TryCompile-58k6i7/Debug/cmTC_54ccf.lib" /MACHINE:X64  /machine:x64 cmTC_54ccf.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_54ccf.vcxproj -> C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-58k6i7\\Debug\\cmTC_54ccf.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_54ccf.dir\\Debug\\cmTC_54ccf.tlog\\unsuccessfulbuild".
          Touching "cmTC_54ccf.dir\\Debug\\cmTC_54ccf.tlog\\cmTC_54ccf.lastbuildstate".
        Done Building Project "C:\\Users\\vigop\\OneDrive\\backup 1\\coding\\Shadow Tech Software 2\\visual studio 2019\\Time Tinkerers\\Time Tinkerers\\CMakeFiles\\CMakeScratch\\TryCompile-58k6i7\\cmTC_54ccf.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.74
        
      exitCode: 0
...
